seed: 42

imagenet:
  train: imagenet/ILSVRC/Data/CLS-LOC/train
  val: imagenet/ILSVRC/Data/CLS-LOC/val

wandb:
  project: deepspeed-tsubame40-tutorial
  entity: <your wandb id>
  run_name: tutorial-tsubame40

train:
  epochs: 1
  log_interval: 4
  save_interval: 60
  max_global_step: -1
  save_path: scratch/deepspeed-tutorial

eval:
  ckpt_path: PATH_TO/mp_rank_00_model_states.pt  
  batch_size: 280
  max_eval: 10
